### ISSUE TITLE
Setting page for app does not appear to be working.

### ISSUE THREAD

**Issue by treavg** [brigmecham/pwc#10]
Reproduce:
1. Log into Picard and proceed to Apps/Overview.
2. Select an app that does not have a home page.
3. Click within the home page box and choose one of the auto generated entries.
4. Click the updated Button.
5. Notice a toaster message appears saying the App was updated.
6. Navigate away from this page and back or refresh and notice the value is no longer set.

I have been using this to try and set either of the **translation_home** or **home** pages as current for the translations app.

When I try to log in with a user account which has the translator role (I also set this role to route to this app) the login takes me to a validation page asking for user data, e.g. name, email, etc.

Using Chrome on Mac

**Comment by brigmecham** [comment]
issue was with editAppForm component.  its been fixed and tested using your translator user.
