### ISSUE TITLE
Version management for Tools->Build2

### ISSUE THREAD

**Issue by treavg** [brigmecham/pwc#12]
When working on custom pages and components I have noticed multiple times in which the history is reverted and I am suddenly working with an older version of the source code.  In these cases I can typically find the most recent version under the history tab and revert before making the changes again.

Potential to reproduce:
1) Create a custom component and save a few changes to both HTML and JS files.
2) Use the preview feature to view the updates.
3) Leave the page and/or close Picard and then return at a later time.
4) Add additional changes to HTML and JS and notice in some cases an older version is set.

When this occurs and I go to the versions tab, the dates will appear one way at first, e.g. "1 day ago", and then if I wait for a minute or so the dates will update on there own, e.g. "15 minutes ago".

**Comment by josepetew** [comment]
Could not reproduce
