### ISSUE TITLE
Cancel Creation of User not responsive

### ISSUE THREAD

**Issue by treavg** [brigmecham/pwc#15]
Navigate to /pwc/admin/users/create-users

When on this page if Cancel is clicked the application remains on the page, would have expected it to transition to /pwc/admin/users/all.

Error from dev console:
Error: Cannot transition to abstract state 'pwc.admin.users'
    at Object.S.P.transitionTo (js_scripts.js?08638855:19)
    at Object.S.P.go (js_scripts.js?08638855:19)
    at js_scripts.js?08638855:19
    at js_scripts.js?08638855:14
    at i (js_scripts.js?08638855:12)
    at js_scripts.js?08638855:12 "Possibly unhandled rejection: {}"

This was using Chrome Version 58.0.3029.110 (64-bit).

**Comment by brigmecham** [comment]
Fixed.
