### ISSUE TITLE
Users added through Picar interface using username as login

### ISSUE THREAD

**Issue by treavg** [brigmecham/pwc#5]
At some point in the process we changed the login for user to be their email instead of their username.  I have only performed minimal testing up to this point but I believe that users added through the Picard interface are still using the username as the login.

Not sure what the best way to handle this is considering Picard will likely have other companies which choose to use the username as the credential for login - maybe a selector on the new user interface to indicate which will be used for login?

**Comment by brigmecham** [comment]
Do you mean you want to be able to login using the users email address?

**Comment by treavg** [comment]
Currently that is the only option via the actual app.  I ran into an issue today where I added a user via the Picard site but then could not login from the application.

**Comment by treavg** [comment]
Closing as this was just a misunderstanding on my part.  If you create the user via Picard and set the email also as the username everything works as expected with Neuros.
