### ISSUE TITLE
Growing tool bar on Data->Search page

### ISSUE THREAD

**Issue by treavg** [brigmecham/pwc#6]
On the Data->Search page using back/forward site navigation causes the left side tool bar to expand into the view.

Using: Chrome on Mac with Picard 0.9.174 devcerevast.
Reproduce: 
1) Navigate to the Data->Search view from the left side tool options.  
2) Click into the 'Current Doctype' dropdown and select a new option.
3) Use the browser back button and then forward button.
4) Should notice that the left side bar grows into the view with each click.

**Comment by josepetew** [comment]
available on next release
