### ISSUE TITLE
Description of dynamic mapping

### ISSUE THREAD

**Issue by treavg** [brigmecham/pwc#8]
Reading the description under the description under the **dynamic mapping** option on page **Data->Overview**...it appears that the description is backwards.

> Determines if new data must adhere to the doctypes mapping definition. If this is set to true, then documents with fields that are not in the mapping file will not be stored.

However if the checkbox is checked, and dynamic mapping is applied (set true), is it not then also true that documents with fields which are not in the mapping file _will_ be stored?

**Comment by josepetew** [comment]
Fixed, correct version should appear on the next build
